import type {
  DashboardSummary,
  FinancialOverview,
  PatientDetail,
  PatientItem,
  PaymentItem,
  ReportMetrics,
  SessionItem,
} from "../supabase/types";

const patients: PatientItem[] = [
  {
    id: "p-1",
    fullName: "Ana Beatriz Gomes",
    phone: "(11) 98888-1000",
    email: "ana@example.com",
    cpf: "123.456.789-10",
    address: "Rua das Flores, 120 - Apto 42 • Bela Vista • Sao Paulo - SP • CEP 01311-000",
    zipCode: "01311-000",
    street: "Rua das Flores",
    number: "120",
    complement: "Apto 42",
    neighborhood: "Bela Vista",
    city: "Sao Paulo",
    state: "SP",
    birthDate: "1993-06-18",
    notes: "Prefere atendimento presencial nas quartas.",
    sessionPrice: 180,
    isActive: true,
    lastSessionAt: "2026-03-05T14:00:00.000Z",
    nextSessionAt: "2026-03-09T14:00:00.000Z",
  },
  {
    id: "p-2",
    fullName: "Marcos Paulo Lima",
    phone: "(11) 97777-2000",
    email: "marcos@example.com",
    cpf: "234.567.890-21",
    address: "Avenida Paulista, 980 - Sala 6 • Bela Vista • Sao Paulo - SP • CEP 01310-100",
    zipCode: "01310-100",
    street: "Avenida Paulista",
    number: "980",
    complement: "Sala 6",
    neighborhood: "Bela Vista",
    city: "Sao Paulo",
    state: "SP",
    birthDate: "1987-01-22",
    notes: "Atendimento online.",
    sessionPrice: 220,
    isActive: true,
    lastSessionAt: "2026-03-04T17:00:00.000Z",
    nextSessionAt: "2026-03-10T17:00:00.000Z",
  },
  {
    id: "p-3",
    fullName: "Clara Mendes Rocha",
    phone: "(11) 96666-3000",
    email: "clara@example.com",
    cpf: "345.678.901-32",
    address: "Rua Aurora, 55 • Centro • Guarulhos - SP • CEP 07010-030",
    zipCode: "07010-030",
    street: "Rua Aurora",
    number: "55",
    complement: "",
    neighborhood: "Centro",
    city: "Guarulhos",
    state: "SP",
    birthDate: "1998-09-11",
    notes: "Primeira consulta concluida.",
    sessionPrice: 160,
    isActive: true,
    lastSessionAt: "2026-03-03T09:00:00.000Z",
    nextSessionAt: "2026-03-11T09:00:00.000Z",
  },
];

const sessions: SessionItem[] = [
  {
    id: "s-1",
    patientId: "p-1",
    patientName: "Ana Beatriz Gomes",
    startsAt: "2026-03-09T14:00:00.000Z",
    endsAt: "2026-03-09T14:50:00.000Z",
    status: "confirmed",
    confirmationStatus: "pending",
    sessionPrice: 180,
    billingMode: "per_session",
    billingAmount: 180,
    location: "Consultorio",
  },
  {
    id: "s-2",
    patientId: "p-2",
    patientName: "Marcos Paulo Lima",
    startsAt: "2026-03-10T17:00:00.000Z",
    endsAt: "2026-03-10T17:50:00.000Z",
    status: "confirmed",
    confirmationStatus: "confirmed",
    sessionPrice: 220,
    billingMode: "per_session",
    billingAmount: 220,
    location: "Google Meet",
  },
  {
    id: "s-3",
    patientId: "p-3",
    patientName: "Clara Mendes Rocha",
    startsAt: "2026-03-11T09:00:00.000Z",
    endsAt: "2026-03-11T09:50:00.000Z",
    status: "confirmed",
    confirmationStatus: "pending",
    sessionPrice: 160,
    billingMode: "per_session",
    billingAmount: 160,
    location: "Consultorio",
  },
  {
    id: "s-4",
    patientId: "p-1",
    patientName: "Ana Beatriz Gomes",
    startsAt: "2026-03-05T14:00:00.000Z",
    endsAt: "2026-03-05T14:50:00.000Z",
    status: "completed",
    confirmationStatus: "confirmed",
    sessionPrice: 180,
    billingMode: "per_session",
    billingAmount: 180,
    location: "Consultorio",
  },
  {
    id: "s-5",
    patientId: "p-2",
    patientName: "Marcos Paulo Lima",
    startsAt: "2026-03-04T17:00:00.000Z",
    endsAt: "2026-03-04T17:50:00.000Z",
    status: "missed",
    confirmationStatus: "pending",
    sessionPrice: 220,
    billingMode: "per_session",
    billingAmount: 220,
    location: "Google Meet",
  },
];

const payments: PaymentItem[] = [
  {
    id: "pay-1",
    patientId: "p-1",
    sessionId: "s-1",
    patientName: "Ana Beatriz Gomes",
    amount: 180,
    status: "pending",
    billingMode: "per_session",
    dueDate: "2026-03-09",
  },
  {
    id: "pay-2",
    patientId: "p-2",
    sessionId: "s-5",
    patientName: "Marcos Paulo Lima",
    amount: 220,
    status: "overdue",
    billingMode: "per_session",
    dueDate: "2026-03-04",
  },
  {
    id: "pay-3",
    patientId: "p-3",
    sessionId: "s-3",
    patientName: "Clara Mendes Rocha",
    amount: 160,
    status: "paid",
    billingMode: "per_session",
    dueDate: "2026-03-03",
    paidAt: "2026-03-03T13:30:00.000Z",
    receiptPath: "tenant-demo/p-3/comprovante-marco.pdf",
  },
];

export const demoDashboard: DashboardSummary = {
  sessionsToday: 2,
  activePatients: 23,
  monthlyRevenue: 6840,
  pendingPayments: 4,
  todaySessions: sessions.filter((session) => session.startsAt.startsWith("2026-03-09")),
  pendingInvoices: payments.filter((payment) => payment.status !== "paid"),
};

export const demoFinancialOverview: FinancialOverview = {
  totalReceivedMonth: 6840,
  totalPending: 400,
  overdueCount: 1,
  recentPayments: payments,
};

export const demoReportMetrics: ReportMetrics = {
  monthlyRevenue: 6840,
  activePatients: 23,
  completedSessions: 42,
  missedSessions: 3,
};

export const demoPatients = patients;
export const demoSessions = sessions;
export const demoPayments = payments;

export const demoPatientDetails: Record<string, PatientDetail> = {
  "p-1": {
    patient: patients[0],
    anamnesis: {
      id: "a-1",
      status: "completed",
      answers: {
        motivo: "Ansiedade relacionada ao trabalho.",
        objetivo: "Melhorar organizacao da rotina e qualidade do sono.",
        historico: "Ja realizou terapia breve em 2022.",
      },
      shareToken: "token-anamnese-1",
      shareExpiresAt: "2026-03-20T23:59:59.000Z",
      submittedAt: "2026-03-01T15:30:00.000Z",
    },
    records: [
      {
        id: "mr-1",
        sessionId: "s-4",
        createdAt: "2026-03-05T15:00:00.000Z",
        privateNotes: "Paciente aderiu bem ao exercicio de respiracao. Proxima sessao focar em rotina noturna.",
        clinicalSummary: "Sessao de acompanhamento semanal.",
      },
    ],
    payments: payments.filter((payment) => payment.patientId === "p-1"),
    sessions: sessions.filter((session) => session.patientId === "p-1"),
  },
  "p-2": {
    patient: patients[1],
    anamnesis: {
      id: "a-2",
      status: "sent",
      answers: {},
      shareToken: "token-anamnese-2",
      shareExpiresAt: "2026-03-12T23:59:59.000Z",
      submittedAt: null,
    },
    records: [],
    payments: payments.filter((payment) => payment.patientId === "p-2"),
    sessions: sessions.filter((session) => session.patientId === "p-2"),
  },
  "p-3": {
    patient: patients[2],
    anamnesis: null,
    records: [],
    payments: payments.filter((payment) => payment.patientId === "p-3"),
    sessions: sessions.filter((session) => session.patientId === "p-3"),
  },
};
